[package]
name = "rustgram-star-gift"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rustgram-dialog-id = { path = "../dialog-id" }
rustgram-star-gift-attribute = { path = "../star_gift-attribute" }
rustgram-formatted-text = { path = "../formatted-text" }

[dev-dependencies]
serde_json = "1.0"
