[package]
name = "rustgram-dialog-date"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
rustgram-dialog-id = { path = "../dialog-id" }
rustgram-server-message-id = { path = "../server_message-id" }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
serde_json = { workspace = true }
