[package]
name = "rustgram-state-manager"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
rustgram-connectionstate = { path = "../connectionstate" }
rustgram-net = { path = "../net" }

tokio = { workspace = true, features = ["sync", "time"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "test-util"] }
