[package]
name = "rustgram-forum-topic-info"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
rustgram-dialog-id = { path = "../dialog-id" }
rustgram-forum-topic-id = { path = "../forum_topic-id" }
rustgram-forum-topic-icon = { path = "../forum_topic-icon, features = ["serde"] }
serde = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
serde_json = { workspace = true }
