[package]
name = "rustgram-business-recipients"
version.workspace = true
edition.workspace = true

[dependencies]
rustgram-types = { path = "../types" }
serde = { workspace = true, optional = true }

[features]
default = []
serde = ["dep:serde"]
