[package]
name = "rustgram-global-privacy-settings"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
rustgram-star-gift-settings = { path = "../star_gift-settings" }

[dev-dependencies]
rstest.workspace = true
