[package]
name = "rustgram-message-reply-info"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
name = "rustgram_message_reply_info"
path = "src/lib.rs"

[dependencies]
rustgram-types = { path = "../types" }
serde = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
