[package]
name = "rustgram-suggested-post"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

description = "Suggested post information for Telegram client"

[features]
default = []
serde = ["dep:serde", "dep:serde_json", "rustgram-suggested-post-price/serde"]

[dependencies]
rustgram-suggested-post-price = { path = "../suggested_post-price" }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }

[dev-dependencies]
bincode = { workspace = true }

[lints]
workspace = true
