[package]
name = "rustgram-user"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
rustgram-accent-color-id = { path = "../accent_color-id" }
rustgram-active-story-state = { path = "../active_story-state" }
rustgram-emoji-status = { path = "../emoji-status" }
rustgram-usernames = { path = "../usernames" }
rustgram-verification-status = { path = "../verification-status" }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0"
