[package]
name = "rustgram-changes-processor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

description = "Changes processor for Telegram MTProto client"

[dependencies]

[dev-dependencies]

[lints]
rust = { unexpected-cfgs = "allow" }
clippy = { all = "deny", unwrap-used = "deny", expect-used = "deny" }

[package.metadata.docs.rs]
all-features = true
