[package]
name = "rustgram-story-album"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Story album for Telegram MTProto client"
keywords.workspace = true
categories.workspace = true

[dependencies]
rustgram-story-album-id = { path = "../story_album-id" }
rustgram-file-id = { path = "../file_id" }
serde = { workspace = true, optional = true }

[dev-dependencies]
serde_json.workspace = true

[features]
default = []
serde = ["dep:serde"]
