[package]
name = "rustgram-request-actor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

description = "Request actor for rustgram-client"
keywords = ["telegram", "mtproto", "actor", "request"]
categories = ["async", "concurrency"]

[features]
default = []

[dependencies]
rustgram-actor = { path = "../actor" }
rustgram-promise = { path = "../promise" }
rustgram-td = { path = "../td" }

[dev-dependencies]

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
