[package]
name = "theme"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
rustgram-types = { path = "../types" }

serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
