[package]
name = "rustgram-user-full-info"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
rustgram-types = { path = "../types" }
rustgram-formatted-text = { path = "../formatted-text" }
rustgram-birthdate = { path = "../birthdate" }
rustgram-block-list-id = { path = "../block_list-id" }
rustgram-profile-tab = { path = "../profile-tab" }
rustgram-bot-verification = { path = "../bot-verification" }
rustgram-business-info = { path = "../business-info" }
rustgram-star-rating = { path = "../star-rating" }
rustgram-star-gift-settings = { path = "../star_gift-settings" }
rustgram-file-id = { path = "../file_id" }
serde = { version = "1.0", features = ["derive"] }
