[package]
name = "rustgram-input-message-text"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

description = "Input message text for Telegram client"

[lib]
name = "rustgram_input_message_text"
path = "src/lib.rs"

[dependencies]
rustgram-formatted-text = { path = "../formatted-text" }
rustgram-message-entity = { path = "../message-entity" }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
bincode = { workspace = true }
