[package]
name = "rustgram-input-message-text"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

description = "Input message text for Telegram client"

[lib]
name = "rustgram_input_message_text"
path = "src/lib.rs"

[dependencies]
rustgram_formatted_text = { path = "../formatted_text" }
rustgram_message_entity = { path = "../message_entity" }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
bincode = { workspace = true }
