[package]
name = "rustgram-todo-item"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

description = "ToDo item structure for Telegram client"

[features]
default = []
serde = ["dep:serde", "dep:serde_json"]

[dependencies]
rustgram-formatted-text = { path = "../formatted-text" }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }

[dev-dependencies]
bincode = { workspace = true }

[lints]
workspace = true
