[package]
name = "rustgram-message-thread-db"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
name = "rustgram_message_thread_db"
path = "src/lib.rs"

[dependencies]
rustgram-types = { path = "../types" }
rustgram-forum-topic-id = { path = "../forum_topic-id" }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
