[package]
name = "rustgram_message_copy_options"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
name = "rustgram_message_copy_options"
path = "src/lib.rs"

[dependencies]
rustgram_formatted_text = { path = "../formatted_text" }
rustgram_message_input_reply_to = { path = "../message_input_reply_to" }
rustgram-types = { path = "../types" }
serde = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
